Finally fixed FindAll ver.1.0.2

diff --git a/StringFunctions b/StringFunctions
--- a/StringFunctions
+++ b/StringFunctions
@@ -30,6 +30,7 @@
 #                                                                                   #
 #     ver.1.0.0       - 04.Jun.2020 - Initial release                               #
 #     ver.1.0.1       - 12.Jun.2020 - Rewrite of Find() function for -b support     #
+#     ver.1.0.2       - 14.Jun.2020 - Rewrite of FindAll() function for -m support  #
 #                                                                                   #
 #-----------------------------------------------------------------------------------#
 
@@ -212,6 +213,8 @@ declare -i _RandomString_byteMultiplier_V1KWz7_=8
 
 function _RandomString()            # bash StringClass dd /dev/urandom tr head
 {
+    # $1 - how long do you want the string
+    # $2 - how many iterations 
     local __ret_RandomString_dCY_
     local -i _getByteCount=256
     local -i _charDefault=16
@@ -600,6 +603,7 @@ function _Length()                  # bash wc gawk
         eval "$1=\${_ret_StringLength}"
 
     # END: of the main part
+
     # START - echo out the Help section
     elif [[ $# -eq 1 || "${2:-}" == "-?" || "${2:-}" == "--help" || "${2:-}" == "-h" ]]
     then
@@ -627,7 +631,7 @@ function _Length()                  # bash wc gawk
 function _Find()                    # bash grep -P head         # alias InStr
 {
     # <SIGNATURE>: (1)_result (2)searchPattern (3)someStringToSearch (?4)options
-    # <RETURN>   : (0)<T>Integer or (0)<T>String
+    # <RETURN>   : (0)<T>Integer, (0)<T>String or (0)<T>Array
     # <OPTIONS>  : (?4) -scmb
     # <BACKEND>  : bash, grep -P, head
     # <TEMPLATE> : _Find _theResult "searchPattern" "someStringToSearch"
@@ -716,7 +720,6 @@ function _Find()                    # bash grep -P head         # alias InStr
     
     thePattern="$2"
 
-
     #---------------------------------------------------
     # START - the PCRE grep routines
     #---------------------------------------------------
@@ -740,7 +743,7 @@ function _Find()                    # bash grep -P head         # alias InStr
             local -i _result=$(( ${grepFoundIt%%:*} + 1 ))      # %% - remove after;      from the ':'; * - everything else
             grepFoundIt="${grepFoundIt#*:}"                     #  # - remove before; ahead of the ':'; * - everything in front of the ':''
 
-    # if it didn't
+    # if it didn't ..
     #---------------------------------------------------
     elif [[ ${#grepFoundIt} -eq 0 ]]
     then
@@ -768,149 +771,179 @@ function _Find()                    # bash grep -P head         # alias InStr
 
 function _FindAll()                 # bash grep -P
 {
-    # <SIGNATURE>: (0)_FindAll (1)_resultArray (2)searchPattern (3)someStringToSearch (4?)options
+    # <SIGNATURE>: (1)_resultArray (2)searchPattern (3)someStringToSearch (?4)options
     # <RETURN>   : (0)<T>AADS - Associative Array Definition String; always named 'ArrayOfStrings'
-    # <OPTIONS>  : (0) -hd (1) -im
+    # <OPTIONS>  : (1) -cm
     # <BACKEND>  : bash, grep -P
     # <TEMPLATE> : _FindAll _theResult "searchPattern" "someStringToSearch"
 
-    # small pre-processor to remove '-hd' from the argument list.
-    local -i n=0
-    for arg in $@
-    do
-        let "n+=1"
-        if [[ $arg == "-hd" ]]
-        then
-            set -- "${@:1:n-1}" "${@:n+1}" # remove n'th positional argument - stackoverflow.com/a/23656370
-        fi
-    done
-
-    local -A ArrayOfStrings=()
-    local -i doMultiLineSearch=$FALSE
-    local doCaseInsensitive='-i'
-
-    # START: main part of the function
-    if [[ $# -ge 3 ]] || [[ $# -eq 2 && ${#htmlLines[@]} -gt 0 ]]
-    then
-        
-        # START - determine what the searched string will be
-        if [[ $# -ge 3 ]] && [[ -f $3  ]]
-        then
-                stringToBeSearched="$(< "$3")"
-        
-        elif [[ $# -ge 3 ]]
-        then
-                stringToBeSearched="$3"
-        
-        elif [[ $# -eq 2 ]] && [[ ${#htmlLines[@]} -gt 0 ]]
-        then
-                stringToBeSearched="${htmlLines[@]}"
-        fi
-        # END of searchedString
-
-        # START - set the booleans for the optionals
-        if [[ ! -z ${4:-} ]] && [[ $(_sc Find '([-][i]*[m]{1,}[i]*\b)' ${4:-}) -gt 0 ]]
-        then
-            doMultiLineSearch=$TRUE
-        fi
-
-        if [[ ! -z ${4:-} ]] && [[ $(_sc Find '([-][m]*[i]{1,}[m]*\b)' ${4:-}) -gt 0 ]]
-        then
-            doCaseInsensitive=''
-        fi
-        # END setting the booleans
-
-        #main logic
-
-        thePattern="$2"
-
-        if [[ $doMultiLineSearch -eq $FALSE ]]
-        then
-            foundIt=$(grep -Po $doCaseInsensitive "$thePattern" <<< "$stringToBeSearched") || foundIt=""
-        else
-            exec 3>&2
-            exec 2> /dev/null
-            foundIt=$(grep -Pazob $doCaseInsensitive "(?s)$thePattern" <<< "$stringToBeSearched") || foundIt=""
-            exec 2>&3
-            log -e "$(foundIt=($foundIt))"
-
-        fi
+    [ $_DEBUGGING -eq $TRUE ] && echo -e "\n:DEBUG: Function Arguments for '_FindAll()' are:\n\n $@. \n\n Number of arguments: $#."
     
-        if [[ ${#foundIt} -gt 0 ]] && [[ $doMultiLineSearch -eq $FALSE ]]
-        then
+    local -A ArrayOfStrings=()
+    
+    local stringToBeSearched=''
+    local thePattern=''
+    local grepFoundIt=''
+    
+    local doCaseInsensitive='-i'
+    local -i doMultiLineSearch=$FALSE
 
-            foundIt=($foundIt)
-            nextChunk="$stringToBeSearched"
-            iPos=0
-            iPrevPos=1
-            iPrevLen=0
-            for item in ${foundIt[@]}
-            do
-                #echo -e "::item: $item\n"
-                #searchString="$item"
-                #rest=${stringToBeSearched#*$searchString}
-                #result="$(( ${#stringToBeSearched} - ${#rest} - ${#searchString} +1 ))"
-                #ArrayOfStrings[$result]="$item"
-                iPos=$(_sc Find "$item" "$nextChunk")
-                iLen=$(_sc Len "$item")
-                nextChunk=${nextChunk#*$item}
-                #echo -e "\n $iPos $iLen $nextChunk \n"
-                iCalc=$(( $iPos + $iPrevPos + $iPrevLen - 1 ))
-                #echo -e $iCalc "\n"
-                ArrayOfStrings[$iCalc]="$item"
-                iPrevPos=$iCalc
-                iPrevLen=$iLen
-            done
-
-        elif [[ ${#foundIt} -gt 0 ]] && [[ $doMultiLineSearch -eq $TRUE ]]
-        then
-            
-            log -e "$foundIt"
-            keepLooping=$TRUE
-            nextChunk="$foundIt"
-
-            while [[ $keepLooping -eq $TRUE ]]
-            do
-                iPos=0
-                bytePosition=${nextChunk%%:*}
-                iLen=$(_sc Len "$bytePosition")
-                nextChunk=${nextChunk#*:}
-                iPos=$(_sc Find '([[:digit:]]+:{1})' "$nextChunk")
-                item=$(_sc Substring "$nextChunk" 1 $(( iPos - 1 )))
-                
-                if [[ $iPos -gt 0 ]]
-                then
-                    nextChunk=${nextChunk#*$item}
-                else
-                    item="$nextChunk"
-                    keepLooping=$FALSE 
-                fi
-                
-                ArrayOfStrings[$bytePosition]="$item"
-                
-            done
-
-        fi
-
-        eval "$1=\$(declare -p ArrayOfStrings)"
-
-    # END: of the main part
+    #---------------------------------------------------
     # START - echo out the Help section
-    elif [[ $# -eq 1 || "${2:-}" == "-?" || "${2:-}" == "--help" || "${2:-}" == "-h" ]]
+    #---------------------------------------------------
+    if [[ $# -eq 1 || "${2:-}" == "-?" || "${2:-}" == "--help" || "${2:-}" == "-h" ]]
     then
-
-        echo -e "\n The command syntax is: FindAll searchPattern someStringToSearch"
-        echo -e " The return result is an Associative array eg. declare -A someVariable"
-        echo -e " The return result creates a hard-coded variable name - 'ArrayOfStrings'."
+            echo -e "\n The command syntax is: FindAll searchPattern someStringToSearch"
+            echo -e " The return result is an Associative array eg. declare -A someVariable"
+            echo -e " The return result creates a hard-coded variable name - 'ArrayOfStrings'."
+            
+            return 0
         
-    else
+    elif [[ $# -gt 1 ]] && [[ $# -lt 3 ]]
+    then
+            local _
+            echo -e "\n Error - missing arguments."
+            eval "_FindAll _ --help"
+    
+    #---------------------------------------------------
+    # END   - echo out the Help section
+    # START - capture the string and any options 
+    #---------------------------------------------------
+    elif [[ $# -ge 3 ]]
+    then
+            # START - determine what the searched string will be
+            #---------------------------------------------------
+            if [[ -f $3  ]]
+            then
+                    [ $_DEBUGGING -eq $TRUE ] && echo -e "\n:DEBUG: _FindAll()'s string of interest is this file: $3. \n"
+                    stringToBeSearched="$(< $3)"
+            else
+                    [ $_DEBUGGING -eq $TRUE ] && echo -e "\n:DEBUG: _FindAll()'s string of interest is just plain. It is: \n\n ${3}"
+                    stringToBeSearched="${3}"
+            fi
+            #---------------------------------------------------
+            # END   - determine what the searched string will be
 
-        local _result
-        echo -e "\n Error - missing arguments."
-        eval "_FindAll _result --help"
+            # START - set the booleans for the optionals
+            #---------------------------------------------------
+            if [[ -n ${4:-} ]]
+            then
+                    [ $_DEBUGGING -eq $TRUE ] && echo -e "\n:DEBUG: _FindAll() has been sent some option(s)\n"
+
+                    local _option_CaseSensitive
+                    _Find _option_CaseSensitive '[-][m]*[c]{1,1}[m]*\b' "${4:-}"
+                    if [[ $_option_CaseSensitive -eq $TRUE ]] ; then doCaseInsensitive='' ; fi
+
+                    local _option_Multiline
+                    _Find _option_Multiline '[-][c]*[m]{1,1}[c]*\b' "${4:-}"
+                    if [[ $_option_Multiline -eq $TRUE ]] ; then doMultiLineSearch=$TRUE ; fi
+            fi
+            #---------------------------------------------------
+            # END setting the booleans
 
     fi
-    # END of help section
+    #---------------------------------------------------
+    # END   - capture the string and any options 
+    #---------------------------------------------------
+    
+    thePattern="$2"
+
+    #---------------------------------------------------
+    # START - the PCRE grep routines
+    #---------------------------------------------------
+    if [[ $doMultiLineSearch -eq $FALSE ]]
+    then
+            grepFoundIt=$(grep -Pob $doCaseInsensitive "$thePattern" <<< "$stringToBeSearched") || foundIt=""
+    else
+            exec 3>&2
+            exec 2> /dev/null
+            grepFoundIt=$(grep -Paznob $doCaseInsensitive "(?s)$thePattern" <<< "$stringToBeSearched") || foundIt=""
+            exec 2>&3
+    fi
+    #---------------------------------------------------
+    # END   - the PCRE grep routines
+    #---------------------------------------------------
+
+    #echo -e "$grepFoundIt"
+
+    while [[ ${#grepFoundIt} -gt 0 ]] && [[ $doMultiLineSearch -eq $FALSE ]]
+    do
+            grepFoundIt=($grepFoundIt)
+            #echo -e "not multi-line"
+
+            for item in ${grepFoundIt[@]}
+            do
+                    bytePosition=${item%%:*}
+                    theString=${item#*:}
+                    #echo -e "\n$bytePosition\n$theString"
+                    ArrayOfStrings[$bytePosition]="$theString"
+            done
+            grepFoundIt=''
+            break
+    done
+
+    #echo -e "$grepFoundIt"
+
+    local _t12_options="${4:--}b"
+    #local -i outer=0
+    local -i bytePosition=0
+
+    while [[ ${#grepFoundIt} -gt 0 ]] && [[ $doMultiLineSearch -eq $TRUE ]]
+    do
+            # Find xxxxx and store it
+            #------------------------
+            _Find _t12 '(?<=1:)[[:digit:]]+(?=:{1})' "$grepFoundIt" $_t12_options
+            
+            bytePosition=${_t12[0]} && theValue=${_t12[1]}
+
+            if [[ $bytePosition -eq 0 ]]; then exit; fi
+
+            # Remove xxxxx from the front
+            #----------------------------
+            grepFoundIt="${grepFoundIt/1:$theValue:}"
+
+            # Find the next xxxxx so we know the string length
+            #-------------------------------------------------
+            _Find _w33 '(?<=1:)[[:digit:]]+(?=:{1})' "$grepFoundIt" $_t12_options
+
+            stringLength=${_w33[0]} # && echo -e "stringLength=$stringLength, calc=$(( stringLength - 3  ))"
+
+                # If string length = 0, it means we couldn't find any more [:digits:]
+                # which means we're at the end.
+                if [[ $stringLength -eq 0 ]]
+                then
+                        #: && echo -e "\n$theValue\n$grepFoundIt"
+                        ArrayOfStrings[$theValue]="$grepFoundIt"
+                        #echo -e "multi-line"
+                        break
+                fi
+
+            # Store the string
+            #-----------------
+            theString="$(_sc Mid "$grepFoundIt" 1 $(( stringLength - 3  )))" || theString=''
+
+            # Remove the string from the front before looping around again ..
+            #----------------------------------------------------------------
+            grepFoundIt="$(_sc Mid "$grepFoundIt" $(( stringLength - 2 )) '-nl')"
+            
+            #(( outer += 1))
+            # Before looping, check the string
+            #---------------------------------
+            #echo -e "grepFoundIt=$grepFoundIt"
+            if [[ $(_sc Len "$grepFoundIt") -le 5 ]]
+            then
+                    _Find _j27 '(?<=1:)[[:digit:]]+(?=:{1})' "$grepFoundIt" $_t12_options
+                    if [[ ${_j27[0]} -eq 0 ]]
+                    then
+                            theString="$theString$grepFoundIt"
+                    fi
+            fi
+            #echo -e "\n$theValue\n$theString"
+            ArrayOfStrings[$theValue]="$theString"
+
+    done
+
+    eval "$1=\$(declare -p ArrayOfStrings)"
 
 }
 
@@ -1217,30 +1250,26 @@ function _Substring()               # bash                      # alias Mid
     # <TEMPLATE> : _Substring _theResult "someStringToSearch" offset length
 
     # small pre-processor to remove '-hd' from the argument list.
-    local -i n=0
-    for arg in $@
-    do
-        let "n+=1"
-        if [[ $arg == "-hd" ]]
-        then
-            set -- "${@:1:n-1}" "${@:n+1}" # remove n'th positional argument - stackoverflow.com/a/23656370
-        fi
-    done
+    #local -i n=0
+    #for arg in $@
+    #do
+    #    let "n+=1"
+    #    if [[ $arg == "-hd" ]]
+    #    then
+    #        set -- "${@:1:n-1}" "${@:n+1}" # remove n'th positional argument - stackoverflow.com/a/23656370
+    #    fi
+    #done
 
     # main part of the function
 
     local _ret_subString=0
     local -i noLength=$FALSE
 
-    if [[ $# -ge 4 ]] || [[ $# -eq 3 && ${#htmlLines[@]} -gt 0 ]]
+    if [[ $# -ge 4 ]]
     then
 
         # START - determine what the searched string will be
-        if [[ $# -eq 3 ]] && [[ ${#htmlLines[@]} -gt 0 ]]
-        then
-                stringToBeSearched="${htmlLines[@]}"
-        
-        elif [[ $# -ge 4 ]] && [[ -f ${2:-}  ]]
+        if [[ $# -ge 4 ]] && [[ -f ${2:-} ]]
         then
                 stringToBeSearched="$(< ${2:-})"
         
@@ -1597,7 +1626,7 @@ StringClass()
         [ $_DEBUGGING -eq $TRUE ] && echo -e "\n:DEBUG: Inside 'Find' wrapper call"
         local _result__Find
         _Find _result__Find "$@"
-        [ -n "${_result__Find:-}" ] && echo -e "${_result__Find[@]}"
+        [ -n "${_result__Find:-}" ] && echo -e "$_result__Find"
     )
 
     InStr() # Pseudonym / Alias for Find
